CREAR ARRAYS

In [2]:
#Importar la libreria
import numpy as np

In [4]:
a1 =np.array([1,2,3]) #Con una lista
type(a1)

numpy.ndarray

In [6]:
a2 = np.arange(10) #np.arange es un metodo similar al range del tipo list
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a3 = np.zeros((5,2)) #crear un lista de dimensiones, pre-rellenada con zeros
a4 = np.ones((5,2)) #crear un lista de dimensiones, pre-rellenada con zeros

In [11]:
from IPython.display import display
display(a3);display(a4)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
a5 = np.linspace(0,1,11) #Crea un array de 0 a 1 de 11 numeros contando los numeros limite
display(a5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
#Dtype
a5.dtype #Muestra el tipo de dato de a5

dtype('float64')

DIMENSIÓN DE UN ARRAY

In [16]:
display(a1)

array([1, 2, 3])

In [17]:
a1.shape #dimension

(3,)

In [18]:
display(a3)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
a3.shape #Dimension

(5, 2)

In [22]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [23]:
#Son los dos arrays iguales?
np.array_equal(a1D,a2D) #Se usa para saber si son iguales

False

In [24]:
#Reshaping - Permite modificar la estructura del array
new_dims = (1,a1D.shape[0])
a = a1D.reshape(new_dims)

In [27]:
np.array_equal(a,a2D)

True

ACCESO A ELEMENTOS Y SLICING

In [29]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [32]:
a[1,2] # Tanto filas como columnas estan indexados desde 0

5

In [33]:
a = np.arange(10)
b = np.eye(3)
display(a); display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#Slicing de arrays
a[:5] #Toma los 5 primeros elementos

array([0, 1, 2, 3, 4])

In [40]:
b[0:3,1] #Toma todos los elementos de la segunda columna

array([0., 1., 0.])

In [41]:
b[2,0:3] #Toma todos los elementos de la ultima columna

array([0., 0., 1.])

In [42]:
b[:,:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])