OPERACIONES SOBRE ARRAYS

In [2]:
import numpy as np
#Aritmetica
a= np.arange(4)

In [11]:
print("a   = ",a)
print("a + 5 =",a+5)
print("a - 5 =",a-5)
print("a * 5 =",a*2)
print("a / 5 =",a/2)
print("a // 5 =",a//2)
print("-a     =",-a)
print("a ** 2 =",a**2)
print("a % 5 =",a%2)


a   =  [0 1 2 3]
a + 5 = [5 6 7 8]
a - 5 = [-5 -4 -3 -2]
a * 5 = [0 2 4 6]
a / 5 = [0.  0.5 1.  1.5]
a // 5 = [0 0 1 1]
-a     = [ 0 -1 -2 -3]
a ** 2 = [0 1 4 9]
a % 5 = [0 1 0 1]


In [10]:
a+a

array([0, 2, 4, 6])

+ np.add
- np.substract
* np.multiply

In [14]:
#Otras funciones
a = np.arange(4)
b = np.arange(1,5)

display(np.exp(a)) #exponencial
display(np.log(b)) #logaritmo natural
display(np.sqrt(a)) #Raiz cuadrada
display(np.greater(a,b))   #Superior o igual punto a punto

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

Las funciones comen a velocidad de codigo compilado C.
De poder utilizarse se deberian preferir al uso de for loops
Un código Numpy solo con funciones nativas, sin bucles, se le llama código "vectorizado".

In [16]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i = 0
for e1 in a:
    b[i] = e1 + e1
    i+=1

670 ms ± 20.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%%timeit
a+a

1.13 µs ± 26.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


ESTADISTICA Y ALEATORIEDAD

In [19]:
a = np.arange(10)

display(np.mean(a)) #promedio
display(np.median(a)) #mediana

4.5

4.5

In [20]:
np.percentile(a,40) #percentil

3.6

In [21]:
np.random.random(10) #Genera array con 10 numeros aleatorios entre 0 y 1

array([0.69865499, 0.64063501, 0.85766789, 0.06927209, 0.25068323,
       0.8653035 , 0.87862917, 0.38226218, 0.79573839, 0.0707037 ])