CREACION DE FEATURES 

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

X = pd.read_csv('X.csv')
y = X['worldwide_gross']
X = X.drop('worldwide_gross',axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y)


EXISTEN DISTINTAS ESTRATEGIAS DE ESCALAMIENTO DE FEATURES, PERO LA MAS COMUN ES LA ESTANDARIZACION DONDE SE CONVIERTE LA VARIABLE PARA QUE LA DEISTRIBUCION SIGA UNA DISTRIBUCION GAUSSIANA DE MEDIA 0 Y DE DESVIACION ESTANDAR 1.

In [3]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [4]:
scaler.mean_ #Promedio de cada una de las features

array([3.33117432e+07, 2.00206526e+03, 2.12239673e+00, 1.08728458e+02,
       3.98696180e+07, 6.46198830e+00, 4.75851056e+07])

In [5]:
scaler.scale_ #Desviacion estandar de cada una de las features

array([4.18037625e+07, 1.21271591e+01, 7.20497346e-01, 2.31532220e+01,
       2.23899846e+08, 1.06815087e+00, 6.36056855e+07])

In [9]:
scaler.transform(X_train)

array([[-6.83233793e-01,  7.36754422e-01,  3.15897442e-01, ...,
        -1.55737570e-01,  8.78164054e-01, -7.20928267e-01],
       [-7.72938637e-01,  9.84133052e-01,  3.15897442e-01, ...,
         2.61620674e-03,  3.16445651e-01, -6.99033259e-01],
       [ 1.45174150e+00, -5.38146663e-03,  3.15897442e-01, ...,
         2.41761586e-01,  2.09522060e+00,  4.60483666e+00],
       ...,
       [-7.92211754e-02,  8.19213966e-01,  3.15897442e-01, ...,
        -4.40805039e-02,  8.78164054e-01,  2.96879269e-01],
       [-3.18434093e-01,  9.01673509e-01,  3.15897442e-01, ...,
        -8.87433304e-02,  1.53350219e+00,  1.42797995e-01],
       [-7.49017345e-01,  7.36754422e-01, -4.75222751e-01, ...,
        -1.77622355e-01, -3.38892487e-01,  1.15434217e-02]])

In [10]:
x_train_scaled, X_test_scaled = (scaler.transform(X_train), scaler.transform(X_test))

In [12]:
from sklearn.linear_model import Lasso

model = Lasso()
model_scaled = Lasso()

model.fit(X_train,y_train)
model_scaled.fit(x_train_scaled,y_train)

Lasso()

In [13]:
print(model.score(X_test,y_test))
print(model_scaled.score(X_test_scaled,y_test))

0.8613932816571488
0.8613932810960223


SIMPLIFICAR LAS TRANSFORMACIONES CON PIPELINES

Para hacer el codigo mas reproducible, y evitar tener que aplicar multiples veces una misma transformacion se recomienda utilizar sklearn.pipeline.make_pipeline que permite encadenar transformaciones a los modelos.

In [14]:
from sklearn.pipeline import make_pipeline

model_scaled = make_pipeline(StandardScaler(), Lasso()) #Encadena los dos objetos de sklearn

model_scaled.fit(X_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [15]:
print(model_scaled.score(X_test,y_test))

0.8613932810960223


CREACION NUEVAS DE FEATURES DE FORMA AUTOMATICA

In [17]:
#Ejemplo 
A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
from sklearn.preprocessing import PolynomialFeatures

transformer = PolynomialFeatures(2) #Grado del polinomio
#Solo se transforma una vez por lo tanto se fit y se transforma al mismo tiempo
transformer.fit_transform(A) #



#PolynomialFeatures transforma una matriz (A1,A2) = (1,A1,A2,A1^2, A1*A2,A2^2)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [24]:
#Siguiendo con el proyecto
transformer = PolynomialFeatures(2)
transformer.fit_transform(X).shape

(4104, 36)

In [25]:
 model_poly = make_pipeline(PolynomialFeatures(2), Lasso())
 model_poly.fit(X_train,y_train)
 model_poly.score(X_test,y_test)

0.878752984762311